---
  # Clock
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS
  # Joint states
- ros_topic_name: "/joint_states"
  gz_topic_name: "/world/tm5-700/model/tm5-700/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS
  # TF
- ros_topic_name: "/tf"
  gz_topic_name: "/model/tm5-700/pose"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS
  # Depth image
- ros_topic_name: "/rgbd_camera/depth_image"
  gz_topic_name: "/world/tm5-700/model/tm5-700/link/tm5-700_link7/sensor/rgbd_camera/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
  # Point cloud
- ros_topic_name: "/rgbd_camera/points"
  gz_topic_name: "/world/tm5-700/model/tm5-700/link/tm5-700_link7/sensor/rgbd_camera/depth_image/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS