# # MoveIt uses this configuration for controller management

controller_names:
  - panda_arm_controller
  - panda_hand_controller

panda_arm_controller:
  type: FollowJointTrajectory
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
  action_ns: follow_joint_trajectory
  default: true
panda_hand_controller:
  type: GripperCommand
  joint: panda_finger_joint1
  joints:
    - panda_finger_joint1
  action_ns: gripper_cmd
  default: true